using Net.Pkcs11Interop.Common;

namespace Net.RutokenPkcs11Interop.Common
{
    public enum Extended_CKA : uint
    {
        /* Ключ только для операций с журналом - тип CK_BBOOL */
        CKA_VENDOR_KEY_JOURNAL = (CKA.CKA_VENDOR_DEFINED | 0x2002),
        /* Операция подписи требует ввода PIN - тип CK_BBOOL */
        CKA_VENDOR_KEY_PIN_ENTER = (CKA.CKA_VENDOR_DEFINED | 0x2000),
        /* Операция подписи требует подтверждения - тип CK_BBOOL */
        CKA_VENDOR_KEY_CONFIRM_OP = (CKA.CKA_VENDOR_DEFINED | 0x2001),
        CKA_VENDOR_USER_TYPE = (CKA.CKA_VENDOR_DEFINED | 0x320b),
        CKA_VENDOR_SUPPORTED_PIN_POLICIES = (CKA.CKA_VENDOR_DEFINED | CKF.CKF_ARRAY_ATTRIBUTE | 0x3202),
        CKA_VENDOR_PIN_POLICY_MIN_LENGTH = (CKA.CKA_VENDOR_DEFINED | 0x3203),
        CKA_VENDOR_PIN_POLICY_HISTORY_DEPTH = (CKA.CKA_VENDOR_DEFINED | 0x3204),
        CKA_VENDOR_PIN_POLICY_ALLOW_DEFAULT_PIN_USAGE = (CKA.CKA_VENDOR_DEFINED | 0x3205),
        CKA_VENDOR_PIN_POLICY_DIGIT_REQUIRED = (CKA.CKA_VENDOR_DEFINED | 0x3206),
        CKA_VENDOR_PIN_POLICY_UPPERCASE_REQUIRED = (CKA.CKA_VENDOR_DEFINED | 0x3207),
        CKA_VENDOR_PIN_POLICY_LOWERCASE_REQUIRED = (CKA.CKA_VENDOR_DEFINED | 0x3208),
        CKA_VENDOR_PIN_POLICY_SPEC_CHAR_REQUIRED = (CKA.CKA_VENDOR_DEFINED | 0x3209),
        CKA_VENDOR_PIN_POLICY_DIFF_CHARS_REQUIRED = (CKA.CKA_VENDOR_DEFINED | 0x320a),
        CKA_VENDOR_PIN_POLICIES_DELETABLE = (CKA.CKA_VENDOR_DEFINED | 0x3201)
    }
}
